import subprocess
import time

print()
print("===============================================================================================================")
print("weber.edu - NS")
print("===============================================================================================================")
print()
print("weber.edu - NSLOOKUP")
print("--------------------")
subprocess.call(["nslookup", "weber.edu"])
print()
print("weber.edu - DIG")
print("---------------")
subprocess.call(["dig", "weber.edu"])
print()
print("weber.edu - HOST")
print("----------------")
subprocess.call(["host", "weber.edu"])
print()

print()
print("===============================================================================================================")
print("deseretnew.com - NS")
print("===============================================================================================================")
print()
print("deseretnews.com - NSLOOKUP")
print("--------------------------")
subprocess.call(["nslookup", "deseretnews.com"])
print()
print("deseretnews.com - DIG")
print("---------------------")
subprocess.call(["dig", "deseretnews.com"])
print()
print("deseretnews.com - HOST")
print("----------------------")
subprocess.call(["host", "deseretnews.com"])
print()

print()
print("===============================================================================================================")
print("weber.edu - MX")
print("===============================================================================================================")
print()
print("weber.edu - MX - NSLOOKUP")
print("-------------------------")
subprocess.call(["nslookup", "-query=mx", "weber.edu"])
print()
print("weber.edu - MX - DIG")
print("--------------------")
subprocess.call(["dig", "weber.edu", "MX", "+short"])
print()
print("weber.edu - MX - HOST")
print("---------------------")
subprocess.call(["host", "-t", "MX", "weber.edu"])
print()

print()
print("===============================================================================================================")
print("gmail.com - MX")
print("===============================================================================================================")
print()
print("gmail.com - MX - NSLOOKUP")
print("-------------------------")
subprocess.call(["nslookup", "-query=mx", "gmail.com"])
print()
print("gmail.com - MX - DIG")
print("--------------------")
subprocess.call(["dig", "gmail.com", "MX", "+short"])
print()
print("gmail.com - MX - HOST")
print("---------------------")
subprocess.call(["host", "-t", "MX", "gmail.com"])
print()


print()
print("===============================================================================================================")
print("yahoo.com - NS")
print("===============================================================================================================")
print()
print("yahoo.com - NSLOOKUP")
print("--------------------")
subprocess.call(["nslookup", "-query=ns", "yahoo.com"])
print()
print("yahoo.com - DIG")
print("---------------")
subprocess.call(["dig", "yahoo.com", "ns", "+short"])
print()
print("yahoo.com - HOST")
print("----------------")
subprocess.call(["host", "-t", "ns", "yahoo.com"])
print()

print()
print("===============================================================================================================")
print("microsoft.com - NS")
print("===============================================================================================================")
print()
print("microsoft.com - NSLOOKUP")
print("------------------------")
subprocess.call(["nslookup", "-query=ns", "microsoft.com"])
print()
print("microsoft.com - DIG")
print("-------------------")
subprocess.call(["dig", "microsoft.com", "ns", "+short"])
print()
print("microsoft.com - HOST")
print("--------------------")
subprocess.call(["host", "-t", "ns", "microsoft.com"])
print()

time.sleep(3)

print()
print("===============================================================================================================")
print("Google DNS - novell.com")
print("===============================================================================================================")
print()
print("novell.com - NSLOOKUP")
print("---------------------")
subprocess.call(["nslookup", "novell.com", "8.8.8.8"])
print()
print("novell.com - DIG")
print("----------------")
subprocess.call(["dig", "@8.8.8.8", "novell.com"])
print()
print("novell.com - HOST")
print("-----------------")
subprocess.call(["host", "novell.com", "8.8.8.8"])
print()

print()
print("===============================================================================================================")
print("www.hp.com - Google DNS")
print("===============================================================================================================")
print()
print("www.hp.com - NSLOOKUP")
print("---------------------")
subprocess.call(["nslookup", "www.hp.com", "8.8.8.8"])
print()
print("www.hp.com - DIG")
print("----------------")
subprocess.call(["dig", "@8.8.8.8", "www.hp.com"])
print()
print("www.hp.com - HOST")
print("-----------------")
subprocess.call(["host", "www.hp.com", "8.8.8.8"])
print()
