INSERT ALL
    INTO genre(genreID, name) VALUES (1, 'Rock')
    INTO genre(genreID, name) VALUES (2, 'Jazz')
    INTO genre(genreID, name) VALUES (3, 'Metal')
    INTO genre(genreID, name) VALUES (4, 'Alternative Punk')
    INTO genre(genreID, name) VALUES (5, 'Rock And Roll')
    INTO genre(genreID, name) VALUES (6, 'Blues')
    INTO genre(genreID, name) VALUES (7, 'Latin')
    INTO genre(genreID, name) VALUES (8, 'Reggae')
    INTO genre(genreID, name) VALUES (9, 'Pop')
    INTO genre(genreID, name) VALUES (10, 'Soundtrack')
    INTO genre(genreID, name) VALUES (11, 'Bossa Nova')
    INTO genre(genreID, name) VALUES (12, 'Easy Listening')
    INTO genre(genreID, name) VALUES (13, 'Heavy Metal')
    INTO genre(genreID, name) VALUES (14, 'RB Soul')
    INTO genre(genreID, name) VALUES (15, 'Electronica Dance')
    INTO genre(genreID, name) VALUES (16, 'World')
    INTO genre(genreID, name) VALUES (17, 'Hip Hop Rap')
    INTO genre(genreID, name) VALUES (18, 'Science Fiction')
    INTO genre(genreID, name) VALUES (19, 'TV Shows')
    INTO genre(genreID, name) VALUES (20, 'Sci Fi and Fantasy')
    INTO genre(genreID, name) VALUES (21, 'Drama')
    INTO genre(genreID, name) VALUES (22, 'Comedy')
    INTO genre(genreID, name) VALUES (23, 'Alternative')
    INTO genre(genreID, name) VALUES (24, 'Classical')
    INTO genre(genreID, name) VALUES (25, 'Opera')
SELECT 1 FROM DUAL;