INSERT ALL
    INTO album(albumID, title, artistID) VALUES (1, 'For Those About To Rock We Salute You', 1)
    INTO album(albumID, title, artistID) VALUES (2, 'Balls to the Wall', 2)
    INTO album(albumID, title, artistID) VALUES (3, 'Restless and Wild', 2)
    INTO album(albumID, title, artistID) VALUES (4, 'Let There Be Rock', 1)
    INTO album(albumID, title, artistID) VALUES (5, 'Big Ones', 3)
    INTO album(albumID, title, artistID) VALUES (6, 'Jagged Little Pill', 4)
    INTO album(albumID, title, artistID) VALUES (7, 'Facelift', 5)
    INTO album(albumID, title, artistID) VALUES (8, 'Warner 25 Anos', 6)
    INTO album(albumID, title, artistID) VALUES (9, 'Plays Metallica By Four Cellos', 7)
    INTO album(albumID, title, artistID) VALUES (10, 'Audioslave', 8)
    INTO album(albumID, title, artistID) VALUES (11, 'Out Of Exile', 8)
    INTO album(albumID, title, artistID) VALUES (12, 'BackBeat Soundtrack', 9)
    INTO album(albumID, title, artistID) VALUES (13, 'The Best Of Billy Cobham', 10)
    INTO album(albumID, title, artistID) VALUES (14, 'Alcohol Fueled Brewtality Live! [Disc 1]', 11)
    INTO album(albumID, title, artistID) VALUES (15, 'Alcohol Fueled Brewtality Live! [Disc 2]', 11)
    INTO album(albumID, title, artistID) VALUES (16, 'Black Sabbath', 12)
    INTO album(albumID, title, artistID) VALUES (17, 'Black Sabbath Vol. 4 (Remaster)', 12)
    INTO album(albumID, title, artistID) VALUES (34, 'Chill: Brazil (Disc 2)', 6)
    INTO album(albumID, title, artistID) VALUES (271, 'Revelations', 8)
SELECT 1 FROM DUAL;